# This project is made by Genouka.
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Copyright by 秋冥散雨_Genouka 2025
# V2.0 version
import os
import base64
import re

var_count = 0
var_dict = {}
def sanitize_var_name(filename):
    # return "genouka_b64_" + re.sub(r'\W|^(?=\d)', '_', filename)
    global var_count
    global var_dict
    var_count += 1
    if filename in var_dict:
        return var_dict[filename]
    var_dict[filename] = "genouka_b64_varqm10" + str(var_count)
    return var_dict[filename]
def to_gml_path(path):
    return path.replace('\\', '/')
def file_to_base64(file_path):
    with open(file_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

def generate_gml_code(output_gml_path, files_dict, working_directory="working_directory"):
    gml_content = []
    gml_content.append('var genouka_file_hint="This script is generated by Qiuming Hardcode Script v2.0.DO NOT MODIFY THIS ONE!!!";\n')
    for filename, b64_data in files_dict.items():
        escaped_data = b64_data.replace('"', '\\"')
        var_name = sanitize_var_name(filename)
        gml_content.append(f'var {var_name} = "{escaped_data}";')
    gml_content.append('var genouka_file;\n')
    # 生成文件写入逻辑
    for filename, _ in files_dict.items():
        var_name = sanitize_var_name(filename)
        gml_path = to_gml_path(f'{working_directory} + "{filename}"')
        gml_content.append(f'''genouka_file = file_text_open_write({gml_path});
file_text_write_string(genouka_file, base64_decode({var_name}));
file_text_close(genouka_file);
''')

    # 写入 GML 文件
    with open(output_gml_path, "w", encoding="utf-8") as f:
        f.write("\n".join(gml_content))

def main():
    source_dir = "files_to_include"
    output_gml = "output_gml_script.gml"
    working_directory = "working_directory"

    files_dict = {}
    for root, _, files in os.walk(source_dir):
        for file in files:
            file_path = os.path.join(root, file)
            relative_path = os.path.relpath(file_path, source_dir)
            files_dict[relative_path] = file_to_base64(file_path)

    generate_gml_code(output_gml, files_dict, working_directory)
    print(f"生成完成: {output_gml}")

if __name__ == "__main__":
    main()